version: '3'

services:
  detect-service:
    build: 
      context: ./python-detect
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ./python-detect/static:/app/static
    restart: always
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 114.114.114.114

networks:
  app-network:
    driver: bridge 