version: '3'

services:
  detect-service:
    build: 
      context: ./python-detect
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./python-detect/static:/app/static
    restart: always 